PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

INSTALL_TARGET        = virt-omap5.dtb virt-exynos5.dtb virt-ls1021a.dtb \
                        virt-mips.dtb virt-mips64.dtb
REQUIRE_HOST_TOOLS    = dtc

include $(L4DIR)/mk/lib.mk
