# This Makefile contains configuration settings for uvmm
# Create a Makefile.config.local to overwrite these settings without git
# interference.

# Emulate PSCI, see arm/hyp_psci.cc (ARM only)
CONFIG_VDEV_PSCI = y

# Emulate a UART 8250 compatible device, see device/uart_8250.cc
CONFIG_VDEV_8250 = y

# Emulate a PrimeCell UART pl011 compatible device, see device/pl011.cc
CONFIG_VDEV_PL011 = y

# Forwarding of Optee SMC calls (ARM only)
CONFIG_VDEV_OPTEE = y

# Support sending power events over virtio input channel
CONFIG_VDEV_VIRTIO_POWER = y

# Forward L4 interrupts
CONFIG_VDEV_VIRQ = y

# Proxy dataspaces and mmio protocol
CONFIG_VDEV_MMIO_PROXY = y

# Mmio-based device for triggering system events (shutdown, reboot)
CONFIG_VDEV_SYSCTL = y

# Proxy for virtio devices implemented in the guest
CONFIG_VDEV_DEVICE_PROXY = y

# Emulate generic PCIe host bridge (ARM only)
CONFIG_VDEV_DEVICE_PCI_HOST_ECAM_GENERIC = y

# enable the monitoring interface
CONFIG_MONITOR = y
