# This Makefile contains configuration settings for uvmm
# Create a Makefile.config.local to overwrite these settings without git
# interference.

# Emulate a UART 8250 compatible device, see device/uart_8250.cc
CONFIG_VDEV_8250 = y
