# This Makefile contains configuration settings for uvmm
# Create a Makefile.config.local to overwrite these settings without git
# interference.

# Emulate PSCI, see arm/hyp_psci.cc (ARM only)
CONFIG_UVMM_VDEV_PSCI = y

# Emulate a UART 8250 compatible device, see device/uart_8250.cc
CONFIG_UVMM_VDEV_8250 = y

# Emulate a PrimeCell UART pl011 compatible device, see device/pl011.cc
CONFIG_UVMM_VDEV_PL011 = y

# Emulate a pl031 rtc, see device/arm/pl031.cc (ARM only)
CONFIG_UVMM_VDEV_PL031 = y

# Forwarding of Optee SMC calls (ARM only)
CONFIG_UVMM_VDEV_OPTEE = y

# Support sending power events over virtio input channel
CONFIG_UVMM_VDEV_VIRTIO_POWER = y

# Forward L4 interrupts
CONFIG_UVMM_VDEV_VIRQ = y

# Proxy dataspaces and mmio protocol
CONFIG_UVMM_VDEV_MMIO_PROXY = y

# Mmio-based device for triggering system events (shutdown, reboot)
CONFIG_UVMM_VDEV_SYSCTL = y

# Proxy for virtio devices implemented in the guest
CONFIG_UVMM_VDEV_DEVICE_PROXY = y

# Emulate generic PCIe host bridge (ARM only)
CONFIG_UVMM_VDEV_DEVICE_PCI_HOST_ECAM_GENERIC = y

# Support simple framebuffer device
CONFIG_UVMM_VDEV_DEVICE_FRAMEBUFFER = y

# CFI flash backed by a file
CONFIG_UVMM_VDEV_CFI_FLASH = y

# Use a Dataspace as read-only device.
CONFIG_UVMM_VDEV_ROM = y

# Simple BOCHS debug IO-port (0x402) to print from guest on vcon device
CONFIG_UVMM_VDEV_ISA_DEBUG_PORT = n

# enable the monitoring interface
CONFIG_UVMM_MONITOR = y

# Support gzip/zlib compressed kernel images (ARM only)
# requires zlib to be available
CONFIG_UVMM_LOADER_GZIP = y

# Support the ROM loader
CONFIG_UVMM_LOADER_ROM = y

# enable l4rtc backend
CONFIG_UVMM_EXTERNAL_RTC = n

# Support injecting exceptions for unhandled faults (ARM only)
CONFIG_UVMM_FAULT_INJECT = y

# enable Qemu Firmware Interface (needed for Tianocore)
CONFIG_UVMM_QEMU_FW_IF = y
