PKGDIR ?= ../../..
L4DIR  ?= $(PKGDIR)/../..

TARGET = uvmm_dtg
MODE   = host

REQUIRES_LIBS = libfdt

PRIVATE_INCDIR = $(PKGDIR)/tools/uvmm_dtg/build $(PKGDIR)/tools/uvmm_dtg/build/host
VPATH = $(PKGDIR)/tools/uvmm_dtg/build

include $(PKGDIR)/tools/uvmm_dtg/build/Makefile
